//! Decoder for NEXRAD Level 3 (RPG) radar products.
//!
//! Level 3 has no existing Rust decoder as of 2026; this crate fills that gap. It decodes the
//! product container — WMO text header strip, 18-byte Message Header Block, 102-byte Product
//! Description Block, zlib-compressed body — and the graphic Product Symbology Block packets
//! that carry storm-cell attributes: packet 15 (Storm ID), 19 (Hail / HDA), 20 (Mesocyclone/
//! MDA). The tabular alphanumeric block is captured as text for interrogation.
//!
//! Verified against goldens generated by MetPy's `Level3File` (see `tests/`). Layout follows
//! NOAA ICD 2620001 (RPG to Class 1 User).

use std::io::Read;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("message too short: need {need} bytes at {what}, have {have}")]
    Short { what: &'static str, need: usize, have: usize },
    #[error("bad product description block (divider {0}, expected -1)")]
    BadPdb(i16),
}

type Result<T> = std::result::Result<T, Error>;

/// A tracked storm cell (symbology packet 15, "Storm ID").
#[derive(Debug, Clone, PartialEq)]
pub struct StormCell {
    /// Two-character cell id, e.g. "A2".
    pub id: String,
    /// Position east / north of the radar, in km.
    pub x_km: f32,
    pub y_km: f32,
}

/// A hail symbol (symbology packet 19, "HDA").
#[derive(Debug, Clone, PartialEq)]
pub struct Hail {
    pub x_km: f32,
    pub y_km: f32,
    /// Probability of hail (%), probability of severe hail (%).
    pub poh: i16,
    pub posh: i16,
    /// Maximum estimated hail size, in units of 1/4 inch (per ICD).
    pub max_size: u16,
}

/// A mesocyclone / MDA point feature (symbology packet 20).
#[derive(Debug, Clone, PartialEq)]
pub struct Meso {
    pub x_km: f32,
    pub y_km: f32,
    pub kind: String,
}

/// A decoded Level 3 product.
#[derive(Debug, Clone, PartialEq)]
pub struct Level3Product {
    /// Product code (58 = Storm Tracking, 59 = Hail Index, 141 = Mesocyclone, …).
    pub code: i16,
    /// Radar latitude / longitude (degrees) and height (feet), from the PDB.
    pub lat: f32,
    pub lon: f32,
    pub height_ft: i16,
    pub cells: Vec<StormCell>,
    pub hail: Vec<Hail>,
    pub meso: Vec<Meso>,
    /// Past-position track polylines (symbology packet 23, SCIT), each a list of (x_km, y_km)
    /// points east/north of the radar. Not cell-id tagged; associate by endpoint proximity.
    pub past_tracks: Vec<Vec<(f32, f32)>>,
    /// The tabular alphanumeric block text, if present (storm attributes table).
    pub tabular: Option<String>,
    /// The graphic alphanumeric block text, if present (per-cell STORM ID / DBZM HGT lines).
    pub graphic: Option<String>,
    /// Printable-text extraction over the whole message. Standalone-tabular products (Storm
    /// Structure, Hail) don't always populate `tabular`/`graphic` at the declared offsets, so this
    /// full-message dump is the reliable source for the tolerant, line-based table parsers.
    pub raw_text: Option<String>,
}

/// Decode a Level 3 product from raw file bytes (WMO header + optional zlib body).
pub fn decode(raw: &[u8]) -> Result<Level3Product> {
    let body = strip_wmo(raw);
    let decompressed = zlib_all(body);
    // The decompressed body carries a second WMO abbreviated heading before the message
    // header block (mirrors MetPy stripping the WMO header again post-decompression).
    let msg = strip_wmo(decompressed.as_deref().unwrap_or(body));

    // Offsets in the PDB are half-words from the start of the message header.
    let mut r = Reader::new(msg);
    r.skip("message header block", 18)?; // MHB: code/date/time/len/src/dest/nblocks

    let pdb_start = r.pos;
    let divider = r.i16("pdb divider")?;
    if divider != -1 {
        return Err(Error::BadPdb(divider));
    }
    let lat = r.i32("lat")? as f32 / 1000.0;
    let lon = r.i32("lon")? as f32 / 1000.0;
    let height_ft = r.i16("height")?;
    let code = r.i16("prod_code")?;
    // The three block offsets sit at the PDB tail (bytes 90..102 of the 102-byte PDB).
    r.pos = pdb_start + 90;
    let sym_off = r.u32("sym_off")? as usize;
    let graph_off = r.u32("graph_off")? as usize;
    let tab_off = r.u32("tab_off")? as usize;

    let mut cells = Vec::new();
    let mut hail = Vec::new();
    let mut meso = Vec::new();
    let mut past_tracks = Vec::new();
    if sym_off != 0 {
        // A truncated/empty symbology block (e.g. tabular-only products like Storm Structure)
        // must not abort decoding — keep whatever parsed and still return the tabular blocks.
        let _ = parse_symbology(msg, sym_off * 2, &mut cells, &mut hail, &mut meso, &mut past_tracks);
    }
    let tabular = if tab_off != 0 { parse_text_block(msg, tab_off * 2, msg.len()) } else { None };
    // The graphic block precedes the tabular one; bound its extraction so runs don't bleed across.
    let graphic = if graph_off != 0 {
        let end = if tab_off > graph_off { tab_off * 2 } else { msg.len() };
        parse_text_block(msg, graph_off * 2, end.min(msg.len()))
    } else {
        None
    };

    let raw_text = parse_text_block(msg, 0, msg.len());

    Ok(Level3Product { code, lat, lon, height_ft, cells, hail, meso, past_tracks, tabular, graphic, raw_text })
}

/// Walk the Product Symbology Block's layers, decoding storm-cell packets (15/19/20) and
/// skipping the rest by their declared length.
fn parse_symbology(
    msg: &[u8],
    off: usize,
    cells: &mut Vec<StormCell>,
    hail: &mut Vec<Hail>,
    meso: &mut Vec<Meso>,
    past_tracks: &mut Vec<Vec<(f32, f32)>>,
) -> Result<()> {
    let mut r = Reader::at(msg, off);
    let _divider = r.i16("sym divider")?;
    let _block_id = r.i16("sym block_id")?;
    let _block_len = r.u32("sym block_len")?;
    let nlayers = r.i16("sym nlayers")?.max(0);

    for _ in 0..nlayers {
        let _ldiv = r.i16("layer divider")?;
        let layer_len = r.u32("layer len")? as usize;
        let layer_end = (r.pos + layer_len).min(msg.len());
        while r.pos + 4 <= layer_end {
            let code = r.u16("packet code")?;
            let num_bytes = r.u16("packet len")? as usize;
            let data_start = r.pos;
            let data_end = (data_start + num_bytes).min(layer_end);
            match code {
                15 => {
                    // Storm ID: [x i16, y i16, id 2 chars] * n.
                    while r.pos + 6 <= data_end {
                        let x = r.i16("stormid x")? as f32 * 0.25;
                        let y = r.i16("stormid y")? as f32 * 0.25;
                        let id = r.ascii(2);
                        cells.push(StormCell { id, x_km: x, y_km: y });
                    }
                }
                19 => {
                    // HDA hail: [x, y, POH, POSH, max size] * n.
                    while r.pos + 10 <= data_end {
                        let x = r.i16("hail x")? as f32 * 0.25;
                        let y = r.i16("hail y")? as f32 * 0.25;
                        let poh = r.i16("poh")?;
                        let posh = r.i16("posh")?;
                        let max_size = r.u16("hail size")?;
                        hail.push(Hail { x_km: x, y_km: y, poh, posh, max_size });
                    }
                }
                20 => {
                    // Mesocyclone/MDA point features: [x, y, kind, attr] * n.
                    while r.pos + 8 <= data_end {
                        let x = r.i16("meso x")? as f32 * 0.25;
                        let y = r.i16("meso y")? as f32 * 0.25;
                        let kind = r.u16("meso kind")?;
                        let _attr = r.u16("meso attr")?;
                        meso.push(Meso { x_km: x, y_km: y, kind: meso_kind(kind).to_string() });
                    }
                }
                23 => {
                    // SCIT past-position: a nested stream of (subcode u16, sublen u16, data)
                    // sub-packets; subcode 6 is a linked vector = one past-track polyline
                    // (i16 x/y pairs scaled by 0.25 km). Other sub-packets are skipped by length.
                    let mut sp = data_start;
                    while sp + 4 <= data_end {
                        let subcode = u16::from_be_bytes([msg[sp], msg[sp + 1]]);
                        let sublen = u16::from_be_bytes([msg[sp + 2], msg[sp + 3]]) as usize;
                        let sub_data = sp + 4;
                        let sub_end = (sub_data + sublen).min(data_end);
                        if subcode == 6 {
                            let mut poly = Vec::new();
                            let mut q = sub_data;
                            while q + 4 <= sub_end {
                                let x = i16::from_be_bytes([msg[q], msg[q + 1]]) as f32 * 0.25;
                                let y = i16::from_be_bytes([msg[q + 2], msg[q + 3]]) as f32 * 0.25;
                                poly.push((x, y));
                                q += 4;
                            }
                            if poly.len() >= 2 {
                                past_tracks.push(poly);
                            }
                        }
                        sp = sub_end.max(sp + 4);
                    }
                }
                _ => {}
            }
            // Advance to the next packet regardless of what we decoded.
            r.pos = data_end;
        }
        r.pos = layer_end;
    }
    Ok(())
}

fn meso_kind(kind: u16) -> &'static str {
    match kind {
        1 => "Mesocyclone (ext.)",
        3 => "Mesocyclone",
        5 => "TVS (ext.)",
        6 => "ETVS (ext.)",
        7 => "TVS",
        8 => "ETVS",
        9 => "MDA",
        10 => "MDA (elev.)",
        11 => "MDA (weak)",
        _ => "Feature",
    }
}

/// Collect an alphanumeric block (`off..end`) as readable text (storm attribute / graphic table).
fn parse_text_block(msg: &[u8], off: usize, end: usize) -> Option<String> {
    let end = end.min(msg.len());
    if off + 10 > end {
        return None;
    }
    // The block is (num_chars, chars) line runs behind divider halfwords; extracting printable
    // ASCII runs reproduces the human-readable table without tracking every divider.
    let mut out = String::new();
    let mut run = 0;
    for &b in &msg[off..end] {
        if (0x20..0x7f).contains(&b) {
            out.push(b as char);
            run += 1;
        } else if run > 0 {
            out.push('\n');
            run = 0;
        }
    }
    let text: String =
        out.lines().map(str::trim_end).filter(|l| !l.trim().is_empty()).collect::<Vec<_>>().join("\n");
    (!text.trim().is_empty()).then_some(text)
}

/// Strip the WMO abbreviated-heading text lines that precede the binary message.
fn strip_wmo(buf: &[u8]) -> &[u8] {
    let start = [b"SDUS".as_slice(), b"NXUS", b"NOUS"]
        .iter()
        .find_map(|sig| find(buf, sig))
        .unwrap_or(0);
    let mut pos = start;
    while let Some(nl) = find(&buf[pos..], b"\r\r\n") {
        let line = &buf[pos..pos + nl];
        let texty = nl < 80 && line.iter().all(|&c| c == b' ' || c.is_ascii_graphic());
        if !texty {
            break;
        }
        pos += nl + 3;
        // Stop when the payload (zlib marker or a binary/high byte) begins.
        match buf.get(pos) {
            Some(&c) if c == 0x78 || c < 0x20 => break,
            None => break,
            _ => {}
        }
    }
    &buf[pos..]
}

/// zlib-decompress `buf` (one or more concatenated frames); `None` if it isn't zlib.
fn zlib_all(buf: &[u8]) -> Option<Vec<u8>> {
    if buf.len() < 2 || buf[0] != 0x78 {
        return None;
    }
    let mut out = Vec::new();
    let mut cur = buf;
    while cur.len() >= 2 && cur[0] == 0x78 {
        let mut dec = flate2::read::ZlibDecoder::new(cur);
        let before = out.len();
        if dec.read_to_end(&mut out).is_err() {
            return (out.len() != before).then_some(out);
        }
        let consumed = dec.total_in() as usize;
        if consumed == 0 || consumed >= cur.len() {
            break;
        }
        cur = &cur[consumed..];
    }
    (!out.is_empty()).then_some(out)
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

/// A big-endian cursor over the decoded message.
struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }
    fn at(buf: &'a [u8], pos: usize) -> Self {
        Self { buf, pos }
    }
    fn take(&mut self, n: usize, what: &'static str) -> Result<&'a [u8]> {
        let end = self.pos + n;
        if end > self.buf.len() {
            return Err(Error::Short { what, need: n, have: self.buf.len().saturating_sub(self.pos) });
        }
        let s = &self.buf[self.pos..end];
        self.pos = end;
        Ok(s)
    }
    fn skip(&mut self, what: &'static str, n: usize) -> Result<()> {
        self.take(n, what).map(|_| ())
    }
    fn i16(&mut self, what: &'static str) -> Result<i16> {
        let b = self.take(2, what)?;
        Ok(i16::from_be_bytes([b[0], b[1]]))
    }
    fn u16(&mut self, what: &'static str) -> Result<u16> {
        let b = self.take(2, what)?;
        Ok(u16::from_be_bytes([b[0], b[1]]))
    }
    fn i32(&mut self, what: &'static str) -> Result<i32> {
        let b = self.take(4, what)?;
        Ok(i32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    }
    fn u32(&mut self, what: &'static str) -> Result<u32> {
        let b = self.take(4, what)?;
        Ok(u32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    }
    /// Read `n` bytes as trimmed printable ASCII.
    fn ascii(&mut self, n: usize) -> String {
        let end = (self.pos + n).min(self.buf.len());
        let s: String = self.buf[self.pos..end]
            .iter()
            .filter(|&&c| (0x20..0x7f).contains(&c))
            .map(|&c| c as char)
            .collect();
        self.pos = end;
        s.trim().to_string()
    }
}
