#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export PATH="$HERE/usr/bin:$PATH"
export LD_LIBRARY_PATH="$HERE/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export ESPEAK_DATA_PATH="$HERE/usr/share/espeak-ng-data"
export HOOKECHO_PIPER_DIR="$HERE/usr/lib/hookecho/piper"
exec "$HERE/usr/bin/hookecho" "$@"
